### ISSUE TITLE
Feature: If PF2e System Proficiency without Level is set to Use Variant Rule

### ISSUE THREAD

**Issue by galaara98** [reyzor1991/pf2e-party-sheet-helper#1]
Can you put a check in for if the system setting "Proficiency without Level" is set to "Use Variant Rule", and recalculate the average check accordingly, otherwise when that setting is in play your suggested default DC is too high.  Or just have a toggle in your settings to use "DC based on average lvl of party" or not

**Comment by reyzor1991** [comment]
For "Proficiency without Level" Need to calculate average Proficiency Rank of skill and then use DC from table 
https://2e.aonprd.com/Rules.aspx?ID=1370
Is it correct?

Example Party
- PC A - skill  Untrained - DC 10
- PB B -  skill Master - DC 25 
- PC C - skill Legendary - DC 30
 => (10+25+30)/3 = 21.6666666667~20

Result 20 is it correct?

**Comment by galaara98** [comment]
im not sure any GM uses it like that.

Generally the table on https://2e.aonprd.com/Rules.aspx?ID=1370 is about the Proficiency needed to do the task, not the Proficiencies of the doer.

so, assuming a GM clicked on a party Skill (to open the "DC of Skill Dialog")
if Proficiency without Level is true, or you have a toggle in the Settings for your Module (which again is a variant rule, so i appreciate you looking at this)

you would present a dialog that used either bullets or a drop down for 
"What Proficiency would normally be needed for this Activity"
and the options would be Untrained, Trained, Expert, Master, Legendary.

probably defaulting to Trained

changing that setting would change the Input Field of "DC of Check" to one of the numbers found at https://2e.aonprd.com/Rules.aspx?ID=1370, but would allow the GM to edit the number 

before pressing "Create DC Template" or "Cancel"

**Comment by galaara98** [comment]
technically you can use a similar interface when proficiency with level exists also... You would just take the average you already calculated from your current research, you could use a drop down of Easy (-2), Average (+0), Hard (+2), Very Hard (+4) , Preposterous (+8), defaulting to Average.
of course always leaving the number editable before the GM presses Create DC Template
