### ISSUE TITLE
Missing tags in module.json

### ISSUE THREAD

**Issue by ottyn** [reyzor1991/pf2e-party-sheet-helper#2]
module.json file is missing the 'url' tag.  This leaves no link to access the repository on the Foundry Addon Modules screen.
![image](https://github.com/reyzor1991/pf2e-party-sheet-helper/assets/97130150/af0f0ed1-0ecf-4e62-ad90-4da47c9e7180)

module.json file is missing the 'changelog' tag.  When module is updated, the update screen has no link to the changelog for users to check what has changed.
![image](https://github.com/reyzor1991/pf2e-party-sheet-helper/assets/97130150/7429f458-e897-4af5-ac09-504a62eb9835)

**Comment by reyzor1991** [comment]
Done
