### ISSUE TITLE
Addon Overview

### ISSUE THREAD

**Issue by Peach774** [reyzor1991/pf2e-party-sheet-helper#5]
It would be nice if the github discussion and/or the foundry package page had pictures and a more thorough description of what each of the features of this module are/do.

**Comment by Nhaaro** [comment]
reyzor is moving it into a shared wiki
https://github.com/reyzor1991/pf2e-wiki/wiki/PF2e-Party-Sheet-Helper

but I agree, it should be nice to see at least a link in this repo
