### ISSUE TITLE
Error in Displaying Character Senses in Party Sheet Overview

### ISSUE THREAD

**Issue by Lanandor** [reyzor1991/pf2e-party-sheet-helper#8]
When mousing the a "Senses" box in the Party Sheet Overview the tooltip displays the system code for low light vision vice simply low light vision. This is repeatable for all characters that have low light vision. Characters were made in Foundry and not imported.

All modules expect PF2e Party Sheet Helper were disabled:
Foundry VTT Version: 11.315
PF2e System Version: 5.12.7
PF2e Party Sheet Helper Version: 0.0.49

![Screenshot 2024-01-24 194330](https://github.com/reyzor1991/pf2e-party-sheet-helper/assets/157668611/862a697b-f1aa-42d2-8190-52c9591a6500)

**Comment by tagnullde** [comment]
Can confirm. 

Console shows this Warning:

![image](https://github.com/reyzor1991/pf2e-party-sheet-helper/assets/44159008/5d7093fc-c2c6-4833-a2ce-2ce378e9ee40)
