### ISSUE TITLE
Additional Character on Char Sheet is difficult to scroll through.

### ISSUE THREAD

**Issue by maplealmond** [reyzor1991/pf2e-party-sheet-helper#9]
Party Sheet Helper adds drag targets for other characters on the character inventory.  This is a nice feature.

However the characters boxes scroll vertically, even though there is lots of horizontal space.  The wasted space is unfortunate.  Any possibility to lay out characters in a more space efficient way?

**Comment by reyzor1991** [comment]
Known issue, will be fixed in next release
